<?xml version="1.0" encoding="utf-8" standalone="yes"?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom"><channel><title>.Net on Learn, Converse, Share</title><link>http://jmeridth.com/tags/.net/</link><description>Recent content in .Net on Learn, Converse, Share</description><generator>Hugo</generator><language>en</language><lastBuildDate>Thu, 12 Apr 2012 00:00:00 -0500</lastBuildDate><atom:link href="http://jmeridth.com/tags/.net/index.xml" rel="self" type="application/rss+xml"/><item><title>NuGet Dependency Versioning and Log4net 1.2.11</title><link>http://jmeridth.com/posts/nuget-dependency-versioning-and-log4net-1.2.11</link><pubDate>Thu, 12 Apr 2012 00:00:00 -0500</pubDate><guid>http://jmeridth.com/posts/nuget-dependency-versioning-and-log4net-1.2.11</guid><description>Yesterday I got bit in the butt with the now infamous new key for strong naming of log4net 1.2.11 situation. We wrote our nuspec file to have a depdency on log4net, like so:
&amp;lt;dependencies&amp;gt; &amp;lt;dependency id=&amp;#34;log4net&amp;#34; version=&amp;#34;1.2.10&amp;#34; /&amp;gt; &amp;lt;/dependencies&amp;gt; Well, to NuGet that means that we allow version 1.2.10 OR greater. Well, since version 1.2.11 had the strong naming change, that caused us dependency issues. We needed to roll back to log4net 1.</description></item><item><title>How to Capture the Exception Message From Assert.Throws in NUnit</title><link>http://jmeridth.com/posts/how-to-capture-exception-message-from-assert-throws-in-nunit/</link><pubDate>Fri, 23 Mar 2012 00:00:00 -0500</pubDate><guid>http://jmeridth.com/posts/how-to-capture-exception-message-from-assert-throws-in-nunit/</guid><description>In the past I’ve used:
[ExpectedException(typeof(CustomException), ExpectedMessage=&amp;#34;blah blah blah&amp;#34;)] to set an exception expectation and assert on the message. With the recent releases of NUnit I’ve finally transitioned all my code to use:
Assert.Throws&amp;lt;CustomException&amp;gt;(() =&amp;gt; someType.someMethod(someValue)); or
Assert.Throws&amp;lt;CustomException&amp;gt;(someType.someMethod); if the method has no parameters.
Only lately have I needed to capture the exception message and validate it. To do this you do the following:
var ex = Assert.Throws&amp;lt;CustomException&amp;gt;(() =&amp;gt; someType.someMethod(someValue)); Assert.</description></item><item><title>Opportunity</title><link>http://jmeridth.com/posts/opportunity/</link><pubDate>Sat, 04 Jun 2011 06:06:10 -0500</pubDate><guid>http://jmeridth.com/posts/opportunity/</guid><description>I’ve been in major transition the last couple months. I decided to leave San Antonio and head to Dallas to work with Joe (@agilejoe) and Marcus (@marcusthebold), both are fellow LosTechies members, at One Technologies. Unfortunately, I’m heading back to San Antonio for personal reasons and would love to help fill the gap I’m leaving. Any other Alt.NET developers who love working at a fast pace, with smart people, on interesting products, should ping Joe or Marcus with your resume.</description></item></channel></rss>